version: "3"
services:
  nginx:
    image: nginx:alpine
    container_name: shop-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/www/
    depends_on:
      - php-fpm
    networks:
      - common

  db:
    image: mysql/mysql-server:latest
    container_name: shop-mysql
    restart: on-failure
    command: [ '--default-authentication-plugin=mysql_native_password' ]
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - TZ=${TZ}
    ports:
      - "3306:3306"
    volumes:
      - ./var:/www/var
      - ${VAR_DIR}/mysql:/var/lib/mysql
      - ${VAR_DIR}/logs/mysql/:/var/log/mysql
    networks:
      - common

  php-fpm:
    image: yiisoftware/yii2-php:7.4-fpm
    container_name: shop-php
    restart: always
    environment:
      - TZ=${TZ}
      - XDEBUG_MODE=debug
      - XDEBUG_SESSION=phpstorm
    working_dir: /www/
    volumes:
      - ./:/www/
    networks:
      - common
    depends_on:
      - db

networks:
  common:
    driver: bridge